---

- name: install docker(Ubuntu)
  apt:
    name:
      - docker.io
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install docker(CentOS)
  command: install docker
  when: ansiblde_distribution == "CentOS"
